### ISSUE TITLE
"Conclusions from workshops" should not be part of Technology session.

### ISSUE THREAD

**Issue by yohell** [neicnordic/neic2017.nordforsk.org#17]

**Comment by bast** [comment]
When exactly will this talk take place then? Before or after the session? How much time?

**Comment by yohell** [comment]
Like in the draft program:

https://docs.google.com/document/d/1UsI0j6nhSGR84UGHyawWg-qjb-CJ8So8znaa5pSmstM/edit#heading=h.3v5kozj89xht

eg in same block, but before Tech1 session proper and not part of it.

/Joel

**Comment by bast** [comment]
25 min, just before Technology session.
