### ISSUE TITLE
Does it make sense to list the individual "sessions" for workshops?

### ISSUE THREAD

**Issue by yohell** [neicnordic/neic2017.nordforsk.org#19]
Like here:

http://neic2017.nordforsk.org/schedule/
http://neic2017.nordforsk.org/workshops/dcache/

The "sessions" are a scheduling resolution technicality that I'd rather like hidden. Spelling it out like this might give people browsing the site the impression that it's encouraged to only "join for one of the sessions" for a workshop, which I can imagine is not appreciated by all (any?) of the workshop organizers.

Maybe we could dim (/remove?) the text from all but the first listed "session" here:

http://neic2017.nordforsk.org/schedule/

And just give start time of first "session" and end time of last "session" on workshop pages, eg here:

http://neic2017.nordforsk.org/workshops/dcache/

**Comment by bast** [comment]
I agree that this can be misleading. So I understand that we want to change http://neic2017.nordforsk.org/workshops/<individual_workshop>/ or do we also want to change how things appear on http://neic2017.nordforsk.org/schedule/?

**Comment by bast** [comment]
And I agree that the multi-session workshop should ideally not be consumed in a fragmented way. This makes it almost impossible to give a good workshop.

**Comment by yohell** [comment]
Ideally, also shown on http://neic2017.nordforsk.org/schedule/, depending on how easy that is to set up and made to look nice. 

If you could have the blocks span visually across the entire day, straight over lunch and everything, that would probably be best imho. We'll just have to communicate to the WS organizers that they are not allowed to work over breaks and lunch, but should shoo everyone out into the break room to network.

**Comment by bast** [comment]
It should be possible. But requires a rewrite because now we are getting into a regime where too many corner cases make the underlying code structure a bit too clunky for this. Need to think about a good way out. A "myopic" solution would be to hardcode directly in the html but that is error prone for dead links.

**Comment by bast** [comment]
I mark it now as solved - hopefully it is more clear now.
