### ISSUE TITLE
Floor layout pic be ugly as heck

### ISSUE THREAD

**Issue by yohell** [neicnordic/neic2017.nordforsk.org#21]
This pic didn't really take well to be scaled up. 

http://neic2017.nordforsk.org/practical/

I feel like I'm going astigmatic looing at it from all the brurring.

**Comment by bast** [comment]
I agree.

**Comment by bast** [comment]
I have now reduced its width - closing the issue. If the issue was about replacing the pic with a more high res one, then please reopen.
