### ISSUE TITLE
Anchor links don't work, top banner obscures what you linked to.

### ISSUE THREAD

**Issue by yohell** [neicnordic/neic2017.nordforsk.org#23]
Example: http://neic2017.nordforsk.org/practical/#conference-dinner

**Comment by bast** [comment]
Indeed - and I have learned that Jekyll apparently automatically creates anchors to headings! Neat! I will fix the offset issue in a moment.

**Comment by bast** [comment]
Need to turn `auto_ids` off and reimplement myself with an offset.
