### ISSUE TITLE
Remove (or scale down?) Workshop: WORKSHOP_NAME heading from workshop page template

### ISSUE THREAD

**Issue by yohell** [neicnordic/neic2017.nordforsk.org#24]
Often, you will want to have a short name for the workshop (to go eg into the schedule overview) and a longer more descriptive name to go onto the workshop page. 

It does not make sense to echo the short name on top of the page in heading size XXXL and then have the more descriptive title under that. Plus "Workshop: " is superfluous. If you get there you already know you are on a workshop page. Case in point:

http://neic2017.nordforsk.org/workshops/system-utilization/

I think it should be removed, or maybe kept but scaled down a great deal so it looks like "breadcrums" style information.

**Comment by bast** [comment]
So we want the "Workshop:" removed - and that is roger. Or is there more that needs to be done? Certainly we don't need the title appearing twice. I wonder whether this is also to be addressed here.

**Comment by bast** [comment]
My opinion is that the "Workshop:" is useful. You might get this info sent as a link and then you might otherwise not know that this is a workshop. For people who click their way to the page, this info is obviously redundant. But I don't insist on it and definitely don't insist on any styling choices.

**Comment by yohell** [comment]
Agreed, it's good to have it there up top as a "classification" of the page, and including the "short title", to keep the association to what's shown in the schedule overview. 

How about we scale it down from !!!MAIN HEADING!!!⁣ size to normal text or thereabouts, and let the workshop page itself set the main heading? Because as it turns out most workshops do want a wordy title that's not really fit for small schedule boxes.

**Comment by bast** [comment]
I have now scaled it down. Workshop abstracts can scale themselves up at will by using less "#" in the headings.
