### ISSUE TITLE
Workshop schedule is unreadable on the phone

### ISSUE THREAD

**Issue by bast** [neicnordic/neic2017.nordforsk.org#27]
Looks ok on the laptop.

**Comment by bast** [comment]
How should it ideally be structured on a small device? @yohell

**Comment by yohell** [comment]
Wide as heck (as in enough to be readable) and let me scroll?

**Comment by bast** [comment]
So we still want same-time workshops to be next to each other and same-rooms to be on the same x axis, right?

**Comment by yohell** [comment]
Or, maybe something like this:

## 2-day workshops (starting Monday, May 29):

* dCache

## Workshops starting Monday, May 29:
     
* Security (full day)
* Containers (full day)
* Monitoring HPC system utilisation (full day)

* Bioethics (morning)
* Data management (morning)
* Deep learning with nVidia (morning)

* Data Services (afternoon)
* Mixed Martial Arts with CodeRefinery (afternoon)

## Workshops starting Tuesday, May 30:

...
